[project]
name = "aiweb-common"
version = "0.1.0"
description = "PoC"
requires-python = ">=3.11"
dependencies = [
  "azure-ai-formrecognizer",
  "azure-core>=1.38.0",
  "streamlit",
  "pandas",
  "pyodbc",
  "langchain_core>=1.0.0",
  "langchain_community",
  "langchain_openai>=1.1.14",
  "langchain_prompty",
  "aiohttp>=3.13.4",
  "pypandoc",
  "pymupdf",
  "python-docx",
  "fastapi",
  "python-magic",
  "python-multipart>=0.0.26",
  "pydantic",
  "pdfplumber",
  "pillow>=12.2.0",
  "lxml>=6.1.0",
  "docx",
  "pytz"
]

# Black formatting
[tool.black]
line-length = 100
include = '\.pyi?$'
exclude = '''
/(
      .eggs         # exclude a few common directories in the
    | .git          # root of the project
    | .hg
    | .mypy_cache
    | .tox
    | venv
    | .venv
    | _build
    | buck-out
    | build
    | dist
    | data
  )/
'''
[tool.autopep8]
max_line_length = 100
ignore = "E501,W6"  # or ["E501", "W6"]
in-place = true
recursive = true
list_fixes= true
aggressive = 2

# iSort
[tool.isort]
profile = "black"
line_length = 100
multi_line_output = 3
include_trailing_comma = true
skip = [".gitignore", ".dockerignore", ".venv/*"]

#Development Dependencies
[project.optional-dependencies]
dev = [
  "black[jupyter]",
  "flake8",
  "isort",
  "mkdocs",
  "mkdocs-material",
  "mkdocstrings[python]",
  "mkdocs-monorepo-plugin"
]

[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["."]
